package org.molgenis.omx.hl7;

import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.Charset;
import java.util.Arrays;

import org.molgenis.framework.db.Database;
import org.molgenis.framework.db.DatabaseException;
import org.molgenis.observ.DataSet;
import org.molgenis.observ.ObservableFeature;
import org.molgenis.observ.ObservationSet;
import org.molgenis.observ.ObservedValue;
import org.molgenis.observ.Protocol;
import org.molgenis.observ.target.OntologyTerm;
import org.testng.annotations.Test;

public class HL7StudyDataSetImporterTest
{
	@Test(expectedExceptions = IllegalArgumentException.class)
	public void HL7ActCategoryImporter()
	{
		new HL7StudyDataSetImporter(null);
	}

	@Test
	public void importData() throws DatabaseException, IOException
	{
		String xml = "<REPC_MT000400UV01.ActCategory xmlns=\"urn:hl7-org:v3\"><component><organizer moodCode=\"EVN\" classCode=\"CATEGORY\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"><!-- Generated by the R4C DCM Model Creator 2011 --><templateId root=\"8A824395-50D1-46e1-BD89-AC77EA4236CB\"/><id root=\"2addb7b5-b5e9-458b-baa2-bb604bf3a1a6\"/><code code=\"75367002\" displayName=\"blood pressure\" codeSystemName=\"SCT\" codeSystem=\"2.16.840.1.113883.6.96\"/><effectiveTime><center value=\"20070914\"/></effectiveTime><recordTarget typeCode=\"RCT\"><patient classCode=\"PAT\"><id root=\"2.16.840.1.113883.2.4.3.8.1000.52\" extension=\"9269\"/><addr><city>City</city></addr><statusCode code=\"active\"/><patientPerson determinerCode=\"INSTANCE\" classCode=\"PSN\"><id root=\"88a5c26f-2eda-405d-8f2b-53d1fe0d6796\"/><name nullFlavor=\"MSK\"/><administrativeGenderCode code=\"F\"/><birthTime value=\"1900\"/><!-- <deceasedTime value=\"\" /> --></patientPerson></patient></recordTarget><!-- Location is de locatie van data verzameling == LRA op poli --><location typeCode=\"LOC\"><healthCareFacility classCode=\"SDLOC\"><code><originalText>LRA op poli</originalText></code></healthCareFacility></location><component typeCode=\"COMP\"><encounter moodCode=\"EVN\" classCode=\"ENC\"><id root=\"2.16.840.1.113883.2.4.3.8.1000.53\" extension=\"1\"/><effectiveTime xsi:type=\"IVL_TS\"><center value=\"20070914\"/></effectiveTime></encounter></component><component typeCode=\"COMP\"><!-- Bovendruk --><observation moodCode=\"EVN\" classCode=\"OBS\"><templateId root=\"8FF6CAD3-1ADF-4c2a-AC88-181CCE39C5D0\"/><code code=\"271649006\" displayName=\"systolic blood pressure\" codeSystemName=\"SCT\" codeSystem=\"2.16.840.1.113883.6.96\"/><value xsi:type=\"PQ\" unit=\"mm[Hg]\" value=\"112\"/><referenceRange typeCode=\"REFV\"><observationRange classCode=\"OBS\" moodCode=\"EVN.CRT\"><text>value referenceRange</text><interpretationCode code=\"N\"/></observationRange></referenceRange></observation></component><component typeCode=\"COMP\"><!-- GemiddeldeArterieleDruk --><observation moodCode=\"EVN\" classCode=\"OBS\"><templateId root=\"FE30D0ED-5FFB-4e18-BB6B-5DEEFE199E6B\"/><code code=\"251074006\" displayName=\"non-invasive mean arterial pressure\" codeSystemName=\"SCT\" codeSystem=\"2.16.840.1.113883.6.96\"/><value xsi:type=\"PQ\" unit=\"mm[Hg]\" value=\"88\"/><referenceRange typeCode=\"REFV\"><observationRange classCode=\"OBS\" moodCode=\"EVN.CRT\"><text>value referenceRange</text><interpretationCode code=\"N\"/></observationRange></referenceRange><referenceRange typeCode=\"REFV\"><observationRange classCode=\"OBS\" moodCode=\"EVN.CRT\"><text>value relative to derivedValue=101</text><interpretationCode code=\"L\"/></observationRange></referenceRange></observation></component><component typeCode=\"COMP\"><!-- Polsdruk --><observation moodCode=\"EVN\" classCode=\"OBS\"><templateId root=\"74CFB1BF-6BDA-4bbd-8B80-75A1295E1C18\"/><code code=\"87179004\" displayName=\"arterial pulse pressure\" codeSystemName=\"SCT\" codeSystem=\"2.16.840.1.113883.6.96\"/><value xsi:type=\"PQ\" unit=\"mm[Hg]\" value=\"84\"/><referenceRange typeCode=\"REFV\"><observationRange classCode=\"OBS\" moodCode=\"EVN.CRT\"><text>value referenceRange</text><interpretationCode code=\"N\"/></observationRange></referenceRange><referenceRange typeCode=\"REFV\"><observationRange classCode=\"OBS\" moodCode=\"EVN.CRT\"><text>value relative to derivedValue=33</text><interpretationCode code=\"H\"/></observationRange></referenceRange></observation></component><component typeCode=\"COMP\"><!-- Onderdruk --><observation moodCode=\"EVN\" classCode=\"OBS\"><templateId root=\"1FFE6882-4030-4983-8FD7-EBEC2028991A\"/><code code=\"271650006\" displayName=\"diastolic blood pressure\" codeSystemName=\"SCT\" codeSystem=\"2.16.840.1.113883.6.96\"/><value xsi:type=\"PQ\" unit=\"mm[Hg]\" value=\"79\"/><referenceRange typeCode=\"REFV\"><observationRange classCode=\"OBS\" moodCode=\"EVN.CRT\"><text>value referenceRange</text><interpretationCode code=\"N\"/></observationRange></referenceRange></observation></component></organizer></component><component><organizer moodCode=\"EVN\" classCode=\"CATEGORY\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"><!-- Generated by the R4C DCM Model Creator 2011 --><templateId root=\"8A824395-50D1-46e1-BD89-AC77EA4236CB\"/><id root=\"2c84a4b8-9f92-4214-9bac-8249cf11e259\"/><code code=\"75367002\" displayName=\"blood pressure\" codeSystemName=\"SCT\" codeSystem=\"2.16.840.1.113883.6.96\"/><effectiveTime><center value=\"20090429\"/></effectiveTime><recordTarget typeCode=\"RCT\"><patient classCode=\"PAT\"><id root=\"2.16.840.1.113883.2.4.3.8.1000.52\" extension=\"61520\"/><addr><city>City</city></addr><statusCode code=\"active\"/><patientPerson determinerCode=\"INSTANCE\" classCode=\"PSN\"><id root=\"2133ce3e-c782-4a87-b3d2-7b20be4e1a87\"/><name nullFlavor=\"MSK\"/><administrativeGenderCode code=\"M\"/><birthTime value=\"1800\"/><!-- <deceasedTime value=\"\" /> --></patientPerson></patient></recordTarget><!-- Location is de locatie van data verzameling == LRA op poli --><location typeCode=\"LOC\"><healthCareFacility classCode=\"SDLOC\"><code><originalText>LRA op poli</originalText></code></healthCareFacility></location><component typeCode=\"COMP\"><encounter moodCode=\"EVN\" classCode=\"ENC\"><id root=\"2.16.840.1.113883.2.4.3.8.1000.53\" extension=\"1\"/><effectiveTime xsi:type=\"IVL_TS\"><center value=\"20090429\"/></effectiveTime></encounter></component><component typeCode=\"COMP\"><!-- Bovendruk --><observation moodCode=\"EVN\" classCode=\"OBS\"><templateId root=\"8FF6CAD3-1ADF-4c2a-AC88-181CCE39C5D0\"/><code code=\"271649006\" displayName=\"systolic blood pressure\" codeSystemName=\"SCT\" codeSystem=\"2.16.840.1.113883.6.96\"/><value xsi:type=\"PQ\" unit=\"mm[Hg]\" value=\"148\"/><referenceRange typeCode=\"REFV\"><observationRange classCode=\"OBS\" moodCode=\"EVN.CRT\"><text>value referenceRange</text><interpretationCode code=\"N\"/></observationRange></referenceRange></observation></component><component typeCode=\"COMP\"><!-- GemiddeldeArterieleDruk --><observation moodCode=\"EVN\" classCode=\"OBS\"><templateId root=\"FE30D0ED-5FFB-4e18-BB6B-5DEEFE199E6B\"/><code code=\"251074006\" displayName=\"non-invasive mean arterial pressure\" codeSystemName=\"SCT\" codeSystem=\"2.16.840.1.113883.6.96\"/><value xsi:type=\"PQ\" unit=\"mm[Hg]\" value=\"102\"/><referenceRange typeCode=\"REFV\"><observationRange classCode=\"OBS\" moodCode=\"EVN.CRT\"><text>value referenceRange</text><interpretationCode code=\"N\"/></observationRange></referenceRange><referenceRange typeCode=\"REFV\"><observationRange classCode=\"OBS\" moodCode=\"EVN.CRT\"><text>value relative to derivedValue=125</text><interpretationCode code=\"L\"/></observationRange></referenceRange></observation></component><component typeCode=\"COMP\"><!-- Polsdruk --><observation moodCode=\"EVN\" classCode=\"OBS\"><templateId root=\"74CFB1BF-6BDA-4bbd-8B80-75A1295E1C18\"/><code code=\"87179004\" displayName=\"arterial pulse pressure\" codeSystemName=\"SCT\" codeSystem=\"2.16.840.1.113883.6.96\"/><value xsi:type=\"PQ\" unit=\"mm[Hg]\" value=\"79\"/><referenceRange typeCode=\"REFV\"><observationRange classCode=\"OBS\" moodCode=\"EVN.CRT\"><text>value referenceRange</text><interpretationCode code=\"N\"/></observationRange></referenceRange><referenceRange typeCode=\"REFV\"><observationRange classCode=\"OBS\" moodCode=\"EVN.CRT\"><text>value relative to derivedValue=69</text><interpretationCode code=\"H\"/></observationRange></referenceRange></observation></component><component typeCode=\"COMP\"><!-- Onderdruk --><observation moodCode=\"EVN\" classCode=\"OBS\"><templateId root=\"1FFE6882-4030-4983-8FD7-EBEC2028991A\"/><code code=\"271650006\" displayName=\"diastolic blood pressure\" codeSystemName=\"SCT\" codeSystem=\"2.16.840.1.113883.6.96\"/><value xsi:type=\"PQ\" unit=\"mm[Hg]\" value=\"79\"/><referenceRange typeCode=\"REFV\"><observationRange classCode=\"OBS\" moodCode=\"EVN.CRT\"><text>value referenceRange</text><interpretationCode code=\"N\"/></observationRange></referenceRange></observation></component></organizer></component></REPC_MT000400UV01.ActCategory>";
		InputStream xmlStream = new ByteArrayInputStream(xml.getBytes(Charset.forName("UTF-8")));
		try
		{
			Database db = mock(Database.class);
			HL7StudyDataSetImporter importer = new HL7StudyDataSetImporter(db);
			importer.importData(xmlStream);

			verify(db).beginTx();

			OntologyTerm ontologyTerm = new OntologyTerm();
			ontologyTerm.setIdentifier("mm[Hg]");
			ontologyTerm.setName("mm[Hg]");
			verify(db).add(Arrays.asList(ontologyTerm));

			ObservableFeature feature0 = new ObservableFeature();
			feature0.setIdentifier("2.16.840.1.113883.2.4.3.8.1000.52");
			feature0.setName("patient");
			feature0.setDataType("string");
			ObservableFeature feature1 = new ObservableFeature();
			feature1.setIdentifier("2.16.840.1.113883.6.96.271649006");
			feature1.setName("systolic blood pressure");
			feature1.setUnit(ontologyTerm);
			feature1.setDataType("decimal");
			ObservableFeature feature2 = new ObservableFeature();
			feature2.setIdentifier("2.16.840.1.113883.6.96.251074006");
			feature2.setName("non-invasive mean arterial pressure");
			feature2.setUnit(ontologyTerm);
			feature2.setDataType("decimal");
			ObservableFeature feature3 = new ObservableFeature();
			feature3.setIdentifier("2.16.840.1.113883.6.96.87179004");
			feature3.setName("arterial pulse pressure");
			feature3.setUnit(ontologyTerm);
			feature3.setDataType("decimal");
			ObservableFeature feature4 = new ObservableFeature();
			feature4.setIdentifier("2.16.840.1.113883.6.96.271650006");
			feature4.setName("diastolic blood pressure");
			feature4.setUnit(ontologyTerm);
			feature4.setDataType("decimal");
			verify(db).add(Arrays.asList(feature0, feature1, feature2, feature3, feature4));

			Protocol protocol = new Protocol();
			protocol.setIdentifier("2.16.840.1.113883.6.96.75367002");
			protocol.setName("blood pressure");
			verify(db).add(protocol);

			DataSet dataSet = new DataSet();
			dataSet.setIdentifier(DataSet.class.getSimpleName());
			dataSet.setName("DataSet");
			verify(db).add(dataSet);

			ObservationSet observationSet0 = new ObservationSet();
			observationSet0.setPartOfDataSet(dataSet);
			ObservationSet observationSet1 = new ObservationSet();
			observationSet1.setPartOfDataSet(dataSet);
			verify(db).add(Arrays.asList(observationSet0, observationSet1));

			ObservedValue value0a = new ObservedValue();
			value0a.setFeature(feature0);
			value0a.setObservationSet(observationSet0);
			value0a.setValue("9269");
			ObservedValue value1a = new ObservedValue();
			value1a.setFeature(feature0);
			value1a.setObservationSet(observationSet0);
			value1a.setValue("61520");

			ObservedValue valueob = new ObservedValue();
			valueob.setFeature(feature1);
			valueob.setObservationSet(observationSet0);
			valueob.setValue("112");
			ObservedValue value0c = new ObservedValue();
			value0c.setFeature(feature2);
			value0c.setObservationSet(observationSet0);
			value0c.setValue("88");
			ObservedValue value0d = new ObservedValue();
			value0d.setFeature(feature3);
			value0d.setObservationSet(observationSet0);
			value0d.setValue("84");
			ObservedValue value0e = new ObservedValue();
			value0e.setFeature(feature4);
			value0e.setObservationSet(observationSet0);
			value0e.setValue("79");
			ObservedValue value1b = new ObservedValue();
			value1b.setFeature(feature1);
			value1b.setObservationSet(observationSet1);
			value1b.setValue("148");
			ObservedValue value1c = new ObservedValue();
			value1c.setFeature(feature2);
			value1c.setObservationSet(observationSet1);
			value1c.setValue("102");
			ObservedValue value1d = new ObservedValue();
			value1d.setFeature(feature3);
			value1d.setObservationSet(observationSet1);
			value1d.setValue("79");
			ObservedValue value1e = new ObservedValue();
			value1e.setFeature(feature4);
			value1e.setObservationSet(observationSet1);
			value1e.setValue("79");
			verify(db).add(
					Arrays.asList(value0a, valueob, value0c, value0d, value0e, value1a, value1b, value1c, value1d,
							value1e));

			verify(db).commitTx();

		}
		finally
		{
			xmlStream.close();
		}
	}
}
