java -cp molgenis_apps/build/classes:molgenis/bin:\
molgenis/lib/ant-1.8.1.jar:\
molgenis/lib/ant-apache-log4j.jar:\
molgenis/lib/aopalliance-1.0.jar:\
molgenis/lib/arq.jar:\
molgenis/lib/asm-3.3.jar:\
molgenis/lib/axiom-api-1.2.7.jar:\
molgenis/lib/axiom-impl-1.2.7.jar:\
molgenis/lib/bcprov-jdk15-1.43.jar:\
molgenis/lib/commons-codec-1.3.jar:\
molgenis/lib/commons-collections-3.2.1.jar:\
molgenis/lib/commons-dbcp-1.2.1.jar:\
molgenis/lib/commons-email-1.2.jar:\
molgenis/lib/commons-fileupload-1.1.jar:\
molgenis/lib/commons-io-2.4.jar:\
molgenis/lib/commons-lang-2.5.jar:\
molgenis/lib/commons-lang3-3.1.jar:\
molgenis/lib/commons-logging-1.1.1.jar:\
molgenis/lib/commons-pool-1.5.2.jar:\
molgenis/lib/concurrent.jar:\
molgenis/lib/cxf-bundle-minimal-2.5.2.jar:\
molgenis/lib/d2rq-0.7.jar:\
molgenis/lib/d2r-server-0.7.jar:\
molgenis/lib/dom4j-1.6.1.jar:\
molgenis/lib/FastInfoset-1.2.7.jar:\
molgenis/lib/freemarker.jar:\
molgenis/lib/ganymed-ssh2-build250.jar:\
molgenis/lib/gson-2.2.1.jar:\
molgenis/lib/hsqldb.jar:\
molgenis/lib/icu4j_3_4.jar:\
molgenis/lib/iri.jar:\
molgenis/lib/jakarta-oro-2.0.8.jar:\
molgenis/lib/javassist-3.12.0.GA.jar:\
molgenis/lib/javax.mail.jar:\
molgenis/lib/javax.servlet.jar:\
molgenis/lib/jaxb-impl-2.2.1.1.jar:\
molgenis/lib/jaxb-xjc-2.2.1.1.jar:\
molgenis/lib/jaxen-1.1.jar:\
molgenis/lib/jdom-1.0.jar:\
molgenis/lib/jena.jar:\
molgenis/lib/jersey-json-1.1.5.jar:\
molgenis/lib/jettison-1.2.jar:\
molgenis/lib/jetty-6.1.21.jar:\
molgenis/lib/jetty-html-6.1.21.jar:\
molgenis/lib/jetty-plus-6.1.21.jar:\
molgenis/lib/jetty-util-6.1.21.jar:\
molgenis/lib/jopenid-1.07.jar:\
molgenis/lib/joseki.jar:\
molgenis/lib/jra-1.0-alpha-4.jar:\
molgenis/lib/js-1.7R1.jar:\
molgenis/lib/json.jar:\
molgenis/lib/jsr311-api-1.1.1.jar:\
molgenis/lib/jta-1.1.jar:\
molgenis/lib/junit-4.8.2.jar:\
molgenis/lib/jxl.jar:\
molgenis/lib/keggapi.jar:\
molgenis/lib/log4j-1.2.15.jar:\
molgenis/lib/lucene-core-3.0.2.jar:\
molgenis/lib/mail.jar:\
molgenis/lib/mindterm.jar:\
molgenis/lib/mockito-all-1.9.5.jar:\
molgenis/lib/mysql-connector-java-5.1.2-beta-bin.jar:\
molgenis/lib/neethi-2.0.4.jar:\
molgenis/lib/ontocat-0.9.9.1.jar:\
molgenis/lib/org.semanticweb.HermiT.jar:\
molgenis/lib/oro-2.0.8.jar:\
molgenis/lib/postgresql-8.3-603.jdbc4.jar:\
molgenis/lib/quartz-1.6.0.jar:\
molgenis/lib/selenium-server-standalone-2.25.0.jar:\
molgenis/lib/serializer-2.7.1.jar:\
molgenis/lib/simplecaptcha-1.2.1.jar:\
molgenis/lib/slf4j-api-1.6.1.jar:\
molgenis/lib/slf4j-log4j12-1.6.1.jar:\
molgenis/lib/smtp.jar:\
molgenis/lib/spring-core-3.1.2.RELEASE.jar:\
molgenis/lib/spring-test-3.1.2.RELEASE.jar:\
molgenis/lib/stax-utils-20060502.jar:\
molgenis/lib/tar.jar:\
molgenis/lib/testng-5.14.10.jar:\
molgenis/lib/tjws-1.99.jar:\
molgenis/lib/validation-api-1.0.0.GA.jar:\
molgenis/lib/velocity-1.6.4.jar:\
molgenis/lib/wsdl4j-1.6.2.jar:\
molgenis/lib/wss4j-1.5.8.jar:\
molgenis/lib/wstx-asl-3.2.8.jar:\
molgenis/lib/xalan-2.7.1.jar:\
molgenis/lib/xercesImpl.jar:\
molgenis/lib/xmlbeans-2.4.0.jar:\
molgenis/lib/xml-resolver-1.2.jar:\
molgenis/lib/xmlrpc-client-3.1.3.jar:\
molgenis/lib/xmlrpc-common-3.1.3.jar:\
molgenis/lib/XmlSchema-1.4.7.jar:\
molgenis/lib/xmlsec-1.4.3.jar:\
molgenis/lib/xmltask.jar:\
molgenis/lib/apache-poi-3.8.2/poi-3.8-20120326.jar:\
molgenis/lib/apache-poi-3.8.2/poi-excelant-3.8-20120326.jar:\
molgenis/lib/apache-poi-3.8.2/poi-ooxml-3.8-20120326.jar:\
molgenis/lib/apache-poi-3.8.2/poi-ooxml-schemas-3.8-20120326.jar:\
molgenis/lib/apache-poi-3.8.2/poi-scratchpad-3.8-20120326.jar:\
molgenis/lib/cobertura/asm.jar:\
molgenis/lib/cobertura/asm-tree.jar:\
molgenis/lib/cobertura/cobertura.jar:\
molgenis/lib/cobertura/log4j.jar:\
molgenis/lib/cobertura/oro.jar:\
molgenis/lib/hibernate/antlr-2.7.6.jar:\
molgenis/lib/hibernate/commons-collections-3.1.jar:\
molgenis/lib/hibernate/dom4j-1.6.1.jar:\
molgenis/lib/hibernate/hibernate3.jar:\
molgenis/lib/hibernate/hibernate-jpa-2.0-api-1.0.0.Final.jar:\
molgenis/lib/hibernate/hibernate-search-3.4.1.Final.jar:\
molgenis/lib/hibernate/javassist-3.12.0.GA.jar:\
molgenis/lib/hibernate/jta-1.1.jar:\
molgenis/lib/hibernate/c3p0-0.9.1.jar:\
molgenis/lib/hibernate/slf4j-api-1.6.1.jar:\
molgenis/lib/hibernate-validator-4.1.0.Final/hibernate-jpa-2.0-api-1.0.0.Final.jar:\
molgenis/lib/hibernate-validator-4.1.0.Final/hibernate-validator-4.1.0.Final.jar:\
molgenis/lib/hibernate-validator-4.1.0.Final/log4j-1.2.14.jar:\
molgenis/lib/hibernate-validator-4.1.0.Final/slf4j-api-1.5.6.jar:\
molgenis/lib/hibernate-validator-4.1.0.Final/slf4j-log4j12-1.5.6.jar:\
molgenis/lib/hibernate-validator-4.1.0.Final/validation-api-1.0.0.GA.jar \
org.molgenis.compute.db.RunPilotsOnBackEnd $1 $2 $3 $4 
