#MOLGENIS walltime=48:00:00 nodes=1 cores=1 mem=4
#INPUTS ${referencePanel},${preparedStudyDir}/chr${chr}.dat,${preparedStudyDir}/chr${chr}.gz,${preparedStudyDir}/chr${chr}.snps
#OUTPUTS ${preparedStudyDir}/chr${chr}.results
#EXES ${minimacBin}
#LOGS log
#TARGETS project,chr

#FOREACH project,chr

inputs "${referenceVCFFile}"
inputs "${preparedStudyDir}/chr${chr}.gz"
inputs "${preparedStudyDir}/chr${chr}.dat"
alloutputsexist "${preparedStudyDir}/chr${chr}.results"

#Minimac requires a file listing markers in the haplotype file. This file can be easily
#generated by extracting the second column from the .dat file.

cut -f 2 -d " " ${preparedStudyDir}/chr${chr}.dat | grep -v Status > ${preparedStudyDir}/chr${chr}.snps

#Example
#cut -f 2 -d " " examples/sample.dat > examples/sample.snps

#The imputation step
${minimacBin} --vcfReference --refHaps ${referenceVCFFile} --haps ${preparedStudyDir}/chr${chr}.gz --snps ${preparedStudyDir}/chr${chr}.snps --rs --rounds 5 --states 200 --probs --phased --prefix ${preparedStudyDir}/chr${chr}.results

# (WARNING: genotypes would be treated as phased regardless of delimiter)
#Example:
#./minimac --vcfReference --refHaps /target/gpfs2/gcc/resources/ImputationReferenceSets/GIANT.phase1_release_v3.20101123.snps_indels_svs.genotypes.refpanel.ALL/chr10.phase1_release_v3.20101123.snps_indels_svs.genotypes.refpanel.ALL.vcf.gz --haps mach1.out.gz --snps examples/sample.snps --rounds 5 --states 200 --prefix results
